import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/lib/i18n";
import { StackProvider } from "@stackframe/stack";
import { stackApp } from "@/lib/stack";
import { Suspense } from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="...">
      <body className="...">
        <StackProvider app={stackApp}>
          <LanguageProvider>
            <Suspense fallback={<div className="p-6 text-sm text-muted-foreground">Loading...</div>}>
              {children}
            </Suspense>
          </LanguageProvider>
        </StackProvider>
      </body>
    </html>
  );
}